import { createContext } from 'react';

export const translations = {
  en: {
    brand: 'Nova Store',
    products: 'Products',
    login: 'Login',
    register: 'Register',
    contact: 'Contact Us',
    cart: 'Cart',
    wishlist: 'Wishlist',
    ourProducts: 'Featured Products',
    page: 'Page',
    of: 'of',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    viewDetails: 'View Details',
    addToCart: 'Add to Cart',
    previous: 'Previous',
    next: 'Next',
    loadingProducts: 'Loading products...',
    failedProducts: 'Failed to load products. Please try again.',
    retry: 'Retry',
    searchPlaceholder: 'Search by product name...',
    noProducts: 'No products matched your current filters.',
    category: 'Category',
    brandLabel: 'Brand',
    rating: 'Rating',
    stock: 'Stock',
    buyNow: 'Buy Now',
    backToProducts: 'Back to Products',
    addedToCart: 'Added to cart',
    yourCartIsEmpty: 'Your cart is empty',
    goAddSomeProducts: 'Go add some products first.',
    shoppingCart: 'Shopping Cart',
    items: 'items',
    item: 'item',
    remove: 'Remove',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    total: 'Total',
    checkout: 'Checkout',
    clearCart: 'Clear Cart',
    continueShopping: 'Continue Shopping',
    quantity: 'Quantity',
    pageNotFound: '404 - Page Not Found',
    goHome: 'Go Home',
    sendMessage: 'Send Us a Message',
    submit: 'Submit',
    successContact: 'Success. We will get back to you soon.',
    registerTitle: 'Create Account',
    loginTitle: 'Login',
    welcomeBack: 'Welcome back!',
    heroBadge: 'Portfolio-ready React storefront',
    heroTitle: 'Clean shopping experience, faster browsing, better product discovery.',
    heroDescription:
      'Explore a polished React and Bootstrap storefront with search, filtering, cart persistence, and a clearer shopping flow.',
    shopNow: 'Shop Now',
    viewCart: 'View Cart',
    allCategories: 'All Categories',
    sortBy: 'Sort by',
    defaultSort: 'Recommended',
    sortPriceLow: 'Price: Low to High',
    sortPriceHigh: 'Price: High to Low',
    sortRating: 'Top Rated',
    results: 'Results',
    avgRating: 'Average Rating',
    filters: 'Filters',
    customerSupport: 'Support',
    secureCheckout: 'Secure Checkout',
    fastDelivery: 'Fast Delivery',
    discoverNow: 'Discover products',
    relatedGallery: 'Product Gallery',
    cartUpdated: 'Cart updated',
    footerText: 'Built with React, Redux Toolkit, Bootstrap, and DummyJSON API.',
    needHelp: 'Need help?',
    browseCollection: 'Browse Collection',
    formIntro: 'Fill in the form and we will reach out shortly.',
    registerIntro: 'Create your account to save your cart and continue shopping later.',
    loginIntro: 'Access your account and continue where you left off.',
    emptyStateTitle: 'Nothing here yet',
    summaryNote: 'Taxes and final payment details are calculated at checkout.',
    saveToWishlist: 'Save to Wishlist',
    removeFromWishlist: 'Remove from Wishlist',
    wishlistSaved: 'Saved to wishlist',
    wishlistRemoved: 'Removed from wishlist',
    wishlistTitle: 'Your wishlist',
    wishlistIntro: 'Save products here, then move them to cart whenever you are ready.',
    emptyWishlist: 'Your wishlist is empty.',
    moveToCart: 'Move to Cart',
    clearWishlist: 'Clear Wishlist',
    wishlistCount: 'Saved items',
    cartCount: 'Cart items',
    loginSuccess: 'You are signed in.',
    registerSuccess: 'Account created successfully.',
    contactEyebrow: 'Customer support',
    loginEyebrow: 'Account access',
    registerEyebrow: 'Join the store',
    wishlistEyebrow: 'Saved for later',
  },
  ar: {
    brand: 'نوفا ستور',
    products: 'المنتجات',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    contact: 'تواصل معنا',
    cart: 'السلة',
    wishlist: 'المفضلة',
    ourProducts: 'المنتجات المميزة',
    page: 'صفحة',
    of: 'من',
    inStock: 'متوفر',
    outOfStock: 'غير متوفر',
    viewDetails: 'عرض التفاصيل',
    addToCart: 'أضف إلى السلة',
    previous: 'السابق',
    next: 'التالي',
    loadingProducts: 'جاري تحميل المنتجات...',
    failedProducts: 'حدث خطأ أثناء تحميل المنتجات. حاول مرة أخرى.',
    retry: 'إعادة المحاولة',
    searchPlaceholder: 'ابحث باسم المنتج...',
    noProducts: 'لا توجد منتجات مطابقة للفلاتر الحالية.',
    category: 'الفئة',
    brandLabel: 'العلامة التجارية',
    rating: 'التقييم',
    stock: 'المخزون',
    buyNow: 'اشتر الآن',
    backToProducts: 'الرجوع للمنتجات',
    addedToCart: 'تمت الإضافة إلى السلة',
    yourCartIsEmpty: 'السلة فارغة',
    goAddSomeProducts: 'ابدأ بإضافة بعض المنتجات أولاً.',
    shoppingCart: 'سلة التسوق',
    items: 'منتجات',
    item: 'منتج',
    remove: 'حذف',
    orderSummary: 'ملخص الطلب',
    subtotal: 'الإجمالي الفرعي',
    shipping: 'الشحن',
    free: 'مجاني',
    total: 'الإجمالي',
    checkout: 'إتمام الشراء',
    clearCart: 'تفريغ السلة',
    continueShopping: 'متابعة التسوق',
    quantity: 'الكمية',
    pageNotFound: '404 - الصفحة غير موجودة',
    goHome: 'الرجوع للرئيسية',
    sendMessage: 'أرسل لنا رسالة',
    submit: 'إرسال',
    successContact: 'تم الإرسال بنجاح. سنتواصل معك قريبًا.',
    registerTitle: 'إنشاء حساب',
    loginTitle: 'تسجيل الدخول',
    welcomeBack: 'أهلاً بعودتك',
    heroBadge: 'واجهة متجر React جاهزة للعرض',
    heroTitle: 'تجربة تسوق أنظف، تصفح أسرع، واكتشاف أوضح للمنتجات.',
    heroDescription:
      'استكشف واجهة متجر محسّنة مبنية بـ React و Bootstrap مع بحث وفلاتر وحفظ للسلة وتدفق استخدام أوضح.',
    shopNow: 'ابدأ التسوق',
    viewCart: 'عرض السلة',
    allCategories: 'كل الفئات',
    sortBy: 'الترتيب',
    defaultSort: 'الأفضل لك',
    sortPriceLow: 'السعر: من الأقل للأعلى',
    sortPriceHigh: 'السعر: من الأعلى للأقل',
    sortRating: 'الأعلى تقييمًا',
    results: 'النتائج',
    avgRating: 'متوسط التقييم',
    filters: 'الفلاتر',
    customerSupport: 'الدعم',
    secureCheckout: 'دفع آمن',
    fastDelivery: 'توصيل سريع',
    discoverNow: 'اكتشف المنتجات',
    relatedGallery: 'معرض المنتج',
    cartUpdated: 'تم تحديث السلة',
    footerText: 'مبني باستخدام React و Redux Toolkit و Bootstrap و DummyJSON API.',
    needHelp: 'تحتاج مساعدة؟',
    browseCollection: 'تصفح المجموعة',
    formIntro: 'املأ النموذج وسنتواصل معك قريبًا.',
    registerIntro: 'أنشئ حسابك لحفظ السلة ومتابعة التسوق لاحقًا.',
    loginIntro: 'ادخل إلى حسابك وأكمل من حيث توقفت.',
    emptyStateTitle: 'لا يوجد شيء هنا الآن',
    summaryNote: 'الضرائب وتفاصيل الدفع النهائية يتم حسابها عند إتمام الشراء.',
    saveToWishlist: 'احفظ في المفضلة',
    removeFromWishlist: 'احذف من المفضلة',
    wishlistSaved: 'تم الحفظ في المفضلة',
    wishlistRemoved: 'تم الحذف من المفضلة',
    wishlistTitle: 'المفضلة الخاصة بك',
    wishlistIntro: 'احفظ المنتجات هنا ثم انقلها إلى السلة وقتما تريد.',
    emptyWishlist: 'المفضلة فارغة.',
    moveToCart: 'انقل إلى السلة',
    clearWishlist: 'تفريغ المفضلة',
    wishlistCount: 'العناصر المحفوظة',
    cartCount: 'عناصر السلة',
    loginSuccess: 'تم تسجيل الدخول بنجاح.',
    registerSuccess: 'تم إنشاء الحساب بنجاح.',
    contactEyebrow: 'دعم العملاء',
    loginEyebrow: 'الدخول للحساب',
    registerEyebrow: 'انضم إلى المتجر',
    wishlistEyebrow: 'محفوظة لوقت لاحق',
  },
};

export const LangContext = createContext(null);
